Add QA technology value
adeo/lmru--tech pull request #13
Opened 2020-09-09 11:33 UTC by N1kbaz

Add QA value. Key value points are formalized in dedicated [Miro dashboard](https://miro.com/app/board/o9J_kqLdvlU=/)

2020-09-10 06:57 UTC, aleksandrregner requested changes

2020-09-10 06:57 UTC, aleksandrregner commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
мб слово опускается заменить?

2020-09-10 06:57 UTC, aleksandrregner commented on content/en/values/technology.md
> +Software testing is conducted in dynamic test environment. Such environment should include all required for testing dependencies (it is recommended to mock out external services). Testing environment
I think it's a misprint here: "from external processed" should be "from external processes"

2020-09-10 06:57 UTC, aleksandrregner commented on content/en/values/technology.md
> +Mock is a system emulator that duplicates system behavior in limited manner but does not reproduce its inner logic.
Can I use stubs or fakes?)

2020-09-10 06:57 UTC, aleksandrregner commented on content/en/values/technology.md
> +It is very important to keep contract – interface description - in actual state.
Sounds like value, should we move it from glossary?

2020-09-10 06:57 UTC, aleksandrregner commented on content/en/values/technology.md
> +Canary deployment helps to reduce negative impact of new feature deployment in case it contains bugs.
add Canary deployment's definition

2020-09-10 06:57 UTC, aleksandrregner commented on content/en/values/technology.md
> +{{< alert color="warning" title="Antipattern" >}}Functional testing in production environment creates real incidents and worsens real users’ experience{{< /alert >}}
maybe we can make this antipattern simpler like "Stress test affects users' experience on a production"

2020-09-10 07:41 UTC, qx57 commented on content/en/values/technology.md
> +It is very important to keep contract – interface description - in actual state.
I think that is clear definition, not value

2020-09-10 07:42 UTC, qx57 commented on content/en/values/technology.md
> +{{< alert color="warning" title="Antipattern" >}}Functional testing in production environment creates real incidents and worsens real users’ experience{{< /alert >}}
Maybe add this wording? Because stress tests is non-functional

2020-09-10 08:24 UTC, dsugrobov requested changes
Thanks for your submission! Some changes requested here...

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +* В каждой продуктовой команде –– как минимум один QA-инженер.
Хороший поинт. Соблюдается ли сейчас эта ценность?

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
Можете пожалуйста уточнить в комментах: соблюдается ли это сейчас и что такое "Работа QA"?

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
Может быть стоит уточнить какими тестами? Автоматическими, юнит, интеграционными.

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +{{< glossary title="Мокирование" >}}
Правильно ли переведён термин? Мб стоит что-то с "Использованием заглушек" или как-то так?

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +{{< alert color="warning" title="Антипаттерн" >}}Функциональное тестирование на продакшене создает реальные инциденты{{< /alert >}}
Уточни пожалуйста, было ли такое у нас в реальности?

2020-09-10 08:24 UTC, dsugrobov commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
У нас сейчас хоть где-то есть?

2020-09-10 08:24 UTC, dsugrobov commented on content/en/values/technology.md
> +### 6. Software testing is as important as software development.
I am not an English expert but this sounds like something wrong with grammar here :(

2020-09-10 08:24 UTC, dsugrobov commented on content/en/values/technology.md
> +* Source code is covered by tests immediately. Do not postpone tests into the backlog!
We are not postponing tests into the backlog.

2020-09-14 08:23 UTC, ilya-lm commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
Лучше, наверное, «тестирование начинается на этапе ...»
Включает в себя: участие в ревью требований, поиск противоречий, формирование пользовательских историй и приемочных критериев.

2020-09-14 08:23 UTC, ilya-lm commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
QA покрывают функционал, код покрывают разработчики же?

2020-09-14 08:23 UTC, ilya-lm commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
Что значит «по возможности»? Наверное, это можно убрать.

2020-09-14 08:23 UTC, ilya-lm commented on content/ru/values/technology.md
> +* Время отклика, мс
Имеет смысл указать ключевой перцентиль

2020-09-17 08:28 UTC, N1kbaz commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
Отрицая, предлагай. "Удаляется" подойдет?

2020-09-17 08:33 UTC, N1kbaz commented on content/en/values/technology.md
> +Mock is a system emulator that duplicates system behavior in limited manner but does not reproduce its inner logic.
I can't see any reason to list all synonyms. But if you think it's crucial I will

2020-09-17 08:36 UTC, N1kbaz commented on content/en/values/technology.md
> +It is very important to keep contract – interface description - in actual state.
> I think that is clear definition, not value

Agree. Value is more vague and should sound like a philosophy but not like a definition from a dictionary

2020-09-17 08:36 UTC, N1kbaz commented on content/en/values/technology.md
> +Canary deployment helps to reduce negative impact of new feature deployment in case it contains bugs.
Is link to corresponding article enough?

2020-09-17 08:54 UTC, N1kbaz commented on content/en/values/technology.md
> +{{< alert color="warning" title="Antipattern" >}}Functional testing in production environment creates real incidents and worsens real users’ experience{{< /alert >}}
@aleksandrregner 
1. Can you explain why it is not simple enough?
2. There are some cases when it's appropriate to do stress testing in production

2020-09-17 08:55 UTC, N1kbaz commented on content/ru/values/technology.md
> +* В каждой продуктовой команде –– как минимум один QA-инженер.
Где-то да, где-то нет. Но к этому нужно стремиться

2020-09-17 09:08 UTC, N1kbaz commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
В нашей продуктовой команде Product content тестировщики принимают участие в обсуждении и анализе задач, описании функциональных требований и т.п.

2020-09-17 09:31 UTC, N1kbaz commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
Не уточняя, какими тестами, подразумеваем, что всеми. Будет странно перечислять здесь все возможные виды тестов, и если что-то пропустим, то кто-то может сослаться на это и не писать тесты

2020-09-17 09:43 UTC, N1kbaz commented on content/ru/values/technology.md
> +{{< glossary title="Мокирование" >}}
Это профессионализм, такой же как "билд", "деплой" и т.п. Если критично, могу заменить на "Использование заглушек", но я бы оставил как есть

2020-09-17 10:35 UTC, N1kbaz commented on content/ru/values/technology.md
> +{{< alert color="warning" title="Антипаттерн" >}}Функциональное тестирование на продакшене создает реальные инциденты{{< /alert >}}
Если не ошибаюсь, Женя Поддубный рассказывал подобную историю.

2020-09-17 10:37 UTC, N1kbaz commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
Были обсуждения этой темы. О практическом применении в Леруа не знаю

2020-09-17 10:43 UTC, vch-lm commented on content/ru/values/technology.md
> +{{< alert color="warning" title="Антипаттерн" >}}Функциональное тестирование на продакшене создает реальные инциденты{{< /alert >}}
Подтверждаю, есть команды или бизнес, которые тестируют на проде и создают реальные (и иногда сложнодиагностируемые) проблемы.

2020-09-17 10:45 UTC, N1kbaz commented on content/en/values/technology.md
> +### 6. Software testing is as important as software development.
We need more English experts here!

2020-09-17 10:46 UTC, N1kbaz commented on content/en/values/technology.md
> +* Source code is covered by tests immediately. Do not postpone tests into the backlog!
Maybe "We do not postpone tests into the backlog"?

2020-09-17 10:47 UTC, N1kbaz commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
Что если заменить эту строчку на "Тесты пишутся сразу, а не откладываются в бэклог"?

2020-09-17 10:50 UTC, N1kbaz commented on content/ru/values/technology.md
> +* Время отклика, мс
В разных командах может использоваться разный перцентиль, поэтому лучше здесь не детализировать. В этом пункте описывается общий принцип, он не должен служить инструкцией или краткой методологией

2020-09-28 12:19 UTC, dsugrobov commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
Будет здорово.

2020-09-28 12:28 UTC, dsugrobov commented on content/en/values/technology.md
> +* Source code is covered by tests immediately. Do not postpone tests into the backlog!
According to the comments below on the Russian version: 
"Тесты пишутся сразу, а не откладываются в бэклог" ->
"Tests create while code is being crafted, and not postpone to the backlog"
(not sure about grammar)

2020-09-28 12:36 UTC, dsugrobov commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
Я тоже не слышал. Предлагаю выпилить.

2020-09-28 12:37 UTC, dsugrobov commented on content/ru/values/technology.md
> +{{< alert color="warning" title="Антипаттерн" >}}Функциональное тестирование на продакшене создает реальные инциденты{{< /alert >}}
Пнятненько. Оставляем.

2020-09-28 12:41 UTC, dsugrobov commented on content/en/values/technology.md
> +Canary deployment helps to reduce negative impact of new feature deployment in case it contains bugs.
No, it's better to have a two-words explanation what is the subject and leave the link to know more.

2020-09-28 12:45 UTC, dsugrobov commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
Это здорово! А есть ещё где? @qx57 @vch-lm ?

2020-09-28 13:05 UTC, aleksandrregner commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
да

2020-09-28 13:18 UTC, aleksandrregner commented on content/en/values/technology.md
> +{{< alert color="warning" title="Antipattern" >}}Functional testing in production environment creates real incidents and worsens real users’ experience{{< /alert >}}
1. I didn't quite understand how functional testing may worse real users' experience
2. yep, it was an example

So the message was "let's make it more simple"

2020-09-29 12:12 UTC, vch-lm commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
@voborgus У нас в ААО пока такого нет. По крайней мере, пока у нас  тестировщики не вовлечены активно

2020-09-30 09:34 UTC, qx57 commented on content/en/values/technology.md
> +{{< alert color="warning" title="Antipattern" >}}Functional testing in production environment creates real incidents and worsens real users’ experience{{< /alert >}}
I think that @N1kbaz said simpliest =) All of Tech portal readers understands functional tests definition and also that that tests may create some parasiting objects in production systems. And about stress test - this type of tests don't run on prod by default (stress tests initially intended for damage system, because usually lead the system in critical or sub-critical condition with bigger error count and failures)

2020-09-30 09:40 UTC, qx57 commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
В PAO есть, с недавнего времени инженеры по тестированию начали принимать участие в проработке требований к фичам. Согласно теории тестирования, QA должны как минимум участвовать в валидации требований - тестировщики помогут предотвратить появление логических ошибок, появление непроверяемых или противоречивых требований и даже снизить количество приемочных сценариев.

2020-09-30 09:45 UTC, qx57 commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
Не согласен, предлагаю оставить. На бэке на постоянной основе работают моки Сбера, ПУЗа и лопуса. Практика правильная, с учетом того, что зачастую предоставляемые сторонними сервисами "песочницы" практически не поддерживаются и могут использовать неактуальные контракты.

2020-09-30 09:48 UTC, qx57 commented on content/en/values/technology.md
> +### 6. Software testing is as important as software development.
If we can't other variants, we may close conversation I think )

2020-09-30 09:54 UTC, qx57 commented on content/ru/values/technology.md
> +* Работа QA начинается на этапе формирования требований.
Поменял и в русской, и в английской версии.

2020-09-30 09:57 UTC, qx57 commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
поправил

2020-09-30 09:57 UTC, qx57 commented on content/en/values/technology.md
> +Software testing is conducted in dynamic test environment. Such environment should include all required for testing dependencies (it is recommended to mock out external services). Testing environment
done

2020-09-30 09:58 UTC, qx57 commented on content/en/values/technology.md
> +Canary deployment helps to reduce negative impact of new feature deployment in case it contains bugs.
Add little definition with article link

2020-09-30 10:00 UTC, qx57 commented on content/en/values/technology.md
> +* Source code is covered by tests immediately. Do not postpone tests into the backlog!
done

2020-09-30 10:00 UTC, qx57 commented on content/ru/values/technology.md
> +* Код покрывается тестами сразу. Тесты не откладываются в бэклог.
исправил

2020-09-30 10:01 UTC, qx57 commented on content/ru/values/technology.md
> +Тестирование системы проводится на динамически поднятом тестовом окружении. Такое окружение по возможности включает в себя все зависимости, необходимые для тестирования (внешние зависимости рекоменду
убрал

2020-09-30 10:01 UTC, qx57 approved these changes

2020-10-01 14:53 UTC, voborgus commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
@qx57 этот коммент — к контрактному тестированию. У нас этого нет, мы не можем голословно писать практики, которых у нас нет :)

2020-10-01 14:54 UTC, voborgus commented on content/en/values/technology.md
> +### 6. Software testing is as important as software development.
Software testing has the same importance as software development.

2020-10-01 14:57 UTC, voborgus commented
@qx57 thank you for the last contribution! A small change and will be ready to merge.

2020-10-01 14:59 UTC, voborgus commented on content/ru/values/technology.md
> +* Тестирование начинается на этапе формирования требований.
Точнее вы описали, что QA уже может участвовать в этом моменте, но текущая формулировка говорит не совсем об этом. Плюс у меня всё ещё большие сомнения в применимости этого подхода по всей компании. @qx57 Есть идеи как проверить есть ли где-то ещё такое?

2020-10-23 10:22 UTC, voborgus commented
ping @qx57

2020-11-23 07:53 UTC, qx57 commented on content/ru/values/technology.md
> +{{< glossary title="Контрактное тестирование" >}}
Пока выпилил, но, надеюсь, скоро мы это добавим =)

2020-11-23 07:56 UTC, qx57 commented on content/en/values/technology.md
> +### 6. Software testing is as important as software development.
done

2020-11-23 08:27 UTC, qx57 commented on content/ru/values/technology.md
> +* Тестирование начинается на этапе формирования требований.
@voborgus, такая практика хорошо себя зарекомендовала уже в нескольких командах (PAO, AAO, Picking) одинаково хорошо для задач backend & frontend. Пример - проверка логики работы фичи/эндпоинта: в этом случае тестирование на этапе разработки логической схемы будет дешевле (не придется переделывать реализацию при обнаружении логических ошибок)

2020-12-02 17:53 UTC, voborgus approved these changes
ok for me now. @aleksandrregner @ValeryLaptev please have a look

2020-12-03 05:36 UTC, ValeryLaptev approved these changes

2020-12-03 11:58 UTC, aleksandrregner approved these changes

2020-12-03 11:59 UTC, merged