Update stack.json
adeo/lmru--tech pull request #15
Opened 2020-10-22 07:48 UTC by alem355

After Autumn meeting about verifying Tech stack, I updated JSON

2020-10-22 08:09 UTC, aleksandrregner approved these changes

2020-10-22 08:13 UTC, voborgus requested changes
can you check please: what you considered as a `language` are not languages itself :(

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='lang'>Kotlin</code> <code class='lang'>Codecept JS_</code>",
bug here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='lang'>Mocha_</code> <code class='lang'>WireMock</code> <code class='lang'>Java</code> <code class='lang'>Umbrella</code> <code class='lang'>TestNG</code> <code clas
bug here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Hold": "<code class='lang'>SOAP</code> <code class='lang'>FTPS /SFTP</code>"
space not needed here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Trial": "VictoriaMetrics",
bug here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
>        "Cases": "Monitoring (application) ",
space not needed here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Trial": "Statuspage",
bug here

2020-10-22 08:13 UTC, voborgus commented on static/stack.json
> +      "Research": "<code class='platform'>Mail.ru</code> code class='platform'>SberCloud Advance</code>",
bug here

2020-10-22 10:39 UTC, voborgus commented on static/stack.json
> +      "Research": "<code class='lang'>Allure Server</code>",
it's not a lang

2020-10-22 10:39 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='tool'>Mocha_</code> <code class='tool'>WireMock</code> <code class='lang'>Java</code> <code class='tool'>Umbrella</code> <code class='tool'>TestNG</code> <code clas
bug in Mocha

2020-10-22 10:40 UTC, voborgus commented on static/stack.json
> +      "Research": "Flutter",
text without tags

2020-10-22 10:43 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='tool'>Ansible</code> <code class='lang'>IaC</code> <code class='lang'>tool</code> <code class='tool'>Terraform</code>",
where is Helm now?

2020-10-22 10:44 UTC, voborgus commented on static/stack.json
> +      "Hold": "<code class='tool'>ZUUL</code> <code class='platform'>Web methods ESB</code> <code class='tool'>Transfile perl</code>"
where is Spring Gateway now? It's not the same with ZUUL

2020-10-22 10:45 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='tool'>Yandex.Tank</code>",
where is HP Performance?

2020-10-22 10:49 UTC, voborgus commented on static/stack.json
> +      "Research": "<code class='platform'>Huawei S3</code>",
where are Ignite and Tarantool?

2020-10-22 10:49 UTC, voborgus commented on static/stack.json
> +      "Hold": ""
maria DB in the hold?

2020-10-22 11:04 UTC, voborgus commented on static/stack.json
> +      "Research": "<code class='lang'>Open Telemetry</code>",
it's not a lang

2020-10-22 11:06 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='lang'>React Native</code> <code class='lang'>LMUI</code> <code class='lang'>Kotlin Multiplatform</code> <code class='lang'>Swift</code>",
Swift duplicated

2020-10-22 11:09 UTC, voborgus commented on static/stack.json
> +      "Research": "",
Drools to hold?

2020-10-22 12:58 UTC, alem355 commented on static/stack.json
> +      "Research": "",
вообще убрали

2020-10-22 12:58 UTC, alem355 commented on static/stack.json
> +      "Research": "<code class='platform'>Huawei S3</code>",
There is no Ignite anymore

2020-10-22 12:58 UTC, alem355 commented on static/stack.json
> +      "Trial": "<code class='tool'>Yandex.Tank</code>",
Added

2020-10-22 13:06 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='lang'>Node.JS</code> <code class='lang'>Java</code> <code class='lang'>Springboot</code> <code class='lang'>Kotlin</code>",
NodeJS Duplicate

2020-10-22 13:06 UTC, voborgus commented on static/stack.json
> +      "Research": "<code class='platform'>Huawei S3</code>",
that's mean it should go to hold, am I right?

2020-10-22 13:08 UTC, voborgus commented on static/stack.json
> +        "Research": "<code class='lang'>Flutter</code>",
platform

2020-10-22 13:09 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='lang'>Mocha</code> <code class='lang'>Java</code> <code class='lang'>JavaScript</code> <code class='tool'>WireMock</code> <code class='lang'>Java</code> <code class
duplicates here

2020-10-22 13:09 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='tool'>Yandex.Tank</code>",
where?

2020-10-22 13:14 UTC, voborgus commented on static/stack.json
> +       "Area": "Data",
wrong spaces at the start of the line

2020-10-22 13:14 UTC, voborgus commented on static/stack.json
> +        "Area": "Frontends",
wrong spaces at the start of the line

2020-10-23 10:21 UTC, voborgus approved these changes
Now it's fine. Thanks @alem355

2020-10-23 10:21 UTC, merged