Stack pages Update
adeo/lmru--tech pull request #24
Opened 2020-11-18 14:12 UTC by alem355

2020-11-18 14:25 UTC, aleksandrregner requested changes

2020-11-18 14:25 UTC, aleksandrregner commented on content/en/stack/_index.md
> +The committee is a community of enterprise architects, technical architects and technical leaders of development teams and IT infrastructure. The main goal of the committee is the selection and recom
at Leroy Merlin Russia
The main goal is.. and then you have a list of two items

2020-11-18 14:25 UTC, aleksandrregner commented on content/en/stack/comittee.md
> +The committee is a community of enterprise architects, technical architects, and technical leaders of development teams and IT infrastructure. The main goal of the committee is to select and recommen
at Leroy Merlin Russia
The definition differs from the definition from stack/_index.md

2020-11-18 14:25 UTC, aleksandrregner commented on content/en/stack/_index.md
> +The committee is a community of enterprise architects, technical architects and technical leaders of development teams and IT infrastructure. The main goal of the committee is the selection and recom
technical leaders of development and IT infrastructure teams

2020-11-18 16:05 UTC, voborgus requested changes

2020-11-18 16:05 UTC, voborgus commented on content/en/stack/comittee.md
> +title: "Технологический комитет"
Change the title please

2020-11-18 16:05 UTC, voborgus commented on content/en/stack/how-to-start.md
> +---
Please fill the document with info from the main page

2020-11-18 16:05 UTC, voborgus commented on content/ru/stack/comittee.md
> +title: "Technology Comittee"
Please translate the title

2020-11-18 16:05 UTC, voborgus commented on content/ru/stack/how-to-start.md
> +---
Please fill the document from the main page

2020-11-19 08:42 UTC, voborgus approved these changes

2020-11-19 08:44 UTC, merged