Update stack.json
adeo/lmru--tech pull request #40
Opened 2021-10-28 13:43 UTC by alem355

annual Update stack Q3

2021-11-08 07:33 UTC, voborgus requested changes

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='tool'>MongoDB</code> <code class='tool'>ClickHouse</code> <code class='tool'>PostgeSQL</code> <code class='platform'>Yandex S3</code> <code class='tool'>Elasticsear
PostgreSQL typo

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Cases": "Apisation",
is this term really exists not only in our heads? Is this term is understandable for anyone? Does it mean I should not create an APIs for example with Kotlin?

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='lang'>React Native</code> <code class='lang'>Jetpack Navigation</code>",
JetPack Navigation is a tool

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Best choice": "<code class='lang'>Swift</code> <code class='tool'>Alamofire</code> <code class='lang'>Kotlin</code> <code class='tool'>Firebase</code> <code class='tool'>Room</code> <code clas
mistake here

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Cases": "Product to Productintegrations mediators",
typo here

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='tool'>Github Actions</code>",
I would say it`s a platform

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='platform'>Werf</code>",
is there a mistake to place a `Werf` here? @pavelchalyk

2021-11-08 07:33 UTC, voborgus commented on static/stack.json
> +      "Trial": "<code class='tool'>GIT Encription</code>",
`GIT Encription` -> `Encrypted in Git`

2022-01-12 11:54 UTC, alem355 commented on static/stack.json
> +      "Cases": "Apisation",
Let's add it for the first time and discuss the next TECH STACK UPDATE MEETING.

2022-01-12 11:54 UTC, alem355 commented on static/stack.json
> +      "Trial": "<code class='lang'>React Native</code> <code class='lang'>Jetpack Navigation</code>",
done

2022-01-12 11:56 UTC, alem355 commented on static/stack.json
> +      "Cases": "Product to Productintegrations mediators",
done

2022-01-12 11:57 UTC, alem355 commented on static/stack.json
> +      "Trial": "<code class='platform'>Werf</code>",
It's not a typo

2022-01-13 12:06 UTC, alem355 commented on static/stack.json
> +      "Best choice": "<code class='tool'>MongoDB</code> <code class='tool'>ClickHouse</code> <code class='tool'>PostgeSQL</code> <code class='platform'>Yandex S3</code> <code class='tool'>Elasticsear
Done

2022-01-13 12:31 UTC, voborgus approved these changes

2022-01-13 12:31 UTC, merged