Devops matrix
adeo/lmru--tech pull request #48
Opened 2022-04-20 10:07 UTC by Joda-repo

This is new page with DevOps matrix

2022-04-25 14:03 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Уведомления об сбоях ведутся через единую систему управления инцидентами и коммуникациями.",
Заменить "единую систему управления инцидентами и коммуникациями" на конкретное название тулзы

2022-04-25 21:15 UTC, altokarev commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Операционная деятельность",
"эксплуатация"?

2022-04-25 21:20 UTC, altokarev commented
а чего матрица "DevOps"-то? такое название, помню, было нарицательным, скорее

может сразу метить шире?

2022-04-25 21:24 UTC, altokarev commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Сбор и анализ логов ведется через инструмент хранения и визуализации. ",
у OpenDistro проблемы; OpenSearch сейчас развивается (в тч и у нас)

2022-04-26 09:58 UTC, Joda-repo commented on content/ru/knowledge/devops-maturity-matrix.md
> +В этой матрице намерено отсутствует четкие инструкции. Мы не хотели ограничивать команды в выборе средств, а указали только "Контроли", которые будут проверяться (высокоуровневые). Грубо говоря если
> Уточнить, кто такие "мы" и почему "вы" можете что-то ограничит
Рабочая группа которая создавала данную матрицу. В которую входят центры компетенции по различным направлениям. Мы и не ограничивали :) В этом и суть.

> Указать кто примет, когда, и почему имеет власть что-то принимать.
Имеются ввиду центры компетенции, по таким направлениям как мониторинг, безопасность и.т.д.

> Кем проверяться, когда. По возможности, избежать лишнего официоза, например в слове "Контроли", которое можно просто назвать "проверками".
Заменил на проверки если так удобнее. 

> Этот тезис считывается с таблицы сам, без предисловия.
Ну не согласен вопросы в чатике такие были, предисловие помогает избежать недопонимания.

2022-04-26 09:59 UTC, Joda-repo commented on content/ru/knowledge/devops-maturity-matrix.md
> +Также с матрицей можно ознакомиться на гугл драйв. [Тут](https://docs.google.com/spreadsheets/d/1P6wYqUcQzeoGrT0Qel0Vr4D-9FAGVPATjNCUUCgR7k8/edit#gid=1710224921)
Я бы оставил пока будет вестись активная работа над комментариями комманд.

2022-04-26 10:01 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Код храниться локально.",
Принято

2022-04-26 10:01 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Код хранится централизовано в VCS системе команды.",
Спорно, подожду пока всех правок.

2022-04-26 10:01 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Код хранится в централизованном VCS компании, используется практика Code Review.",
Спорно, подожду пока всех правок.

2022-04-26 10:03 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга.<abbr data-toggle='tooltip' title='Доступ
> Сделать пункт менее официозным и уточнить что такое "корпоративный инструмент мониторинга"

Мы не указываем конкретную технологию, раньше был Dynatrace, но сейчас пока не знаю. Может прометеус, я уточню когда мы будем работать над комментариями.

2022-04-26 10:05 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга.<abbr data-toggle='tooltip' title='Доступ
> 
> 
> Убрать "Сбор метрик ведется через корпоративный инструмент мониторинга.", так как это присутствует в предыдущем пункте.
> 
> Например, финальный текст может выглядить как-то так: "Настроены технические SLO в {название инструмента}" и коммент обьясняющий технические SLO

Я боюсь возникнет недопонимание, сейчас каждый пункт более менее полный. То есть что нужно для голда то указано. Если делать "лесенкой" боюсь будут логические нестыковки. 

Типа "Код храниться локально" на бронзе, а потом он хранится в VCS

2022-04-26 10:06 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга. Настроены SLO по бизнес метрикам чер
> Убрать "Сбор метрик ведется через корпоративный инструмент мониторинга.", так как это присутствует в предыдущем пункте.
> 
> Например, финальный текст может выглядить как-то так: "Настроены технические и бизнес SLO в {название инструмента}" и коммент обьясняющий бизнес SLO

Я боюсь возникнет недопонимание, сейчас каждый пункт более менее полный. То есть что нужно для голда то указано. Если делать "лесенкой" боюсь будут логические нестыковки.

Типа "Код храниться локально" на бронзе, а потом он хранится в VCS

2022-04-26 10:07 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Cases": "Оповещение",
Американизм какой-то :) , но поставлю Алертинг так как он был в матрице.

2022-04-26 10:09 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Уведомления об сбоях ведутся через единую систему управления инцидентами и коммуникациями.",
Спорно, дождусь комментов.

2022-04-26 10:09 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Уведомления об сбоях ведутся через единую систему управления инцидентами и коммуникациями. Поддержка приложений осуществляется непрерывно на основе матрицы эскалации и расписании деж
Я боюсь возникнет недопонимание, сейчас каждый пункт более менее полный. То есть что нужно для голда то указано. Если делать "лесенкой" боюсь будут логические нестыковки.

Типа "Код храниться локально" на бронзе, а потом он хранится в VCS

2022-04-26 10:31 UTC, altokarev commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Код храниться локально.",
принял - резолви) сложно листать же

2022-04-26 10:41 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Код хранится в централизованном VCS компании, используется практика Code Review."
Спорно, подожду пока всех правок.

2022-04-26 14:17 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Сбор и анализ логов ведется через инструмент хранения и визуализации. ",
Отлично: "Логи собираются и визуализируются с помощью OpenSearch." :)

2022-04-26 14:17 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Операционная деятельность",
Идеально!

2022-04-26 14:20 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга.<abbr data-toggle='tooltip' title='Доступ
При хранении кода в гите, код одновременно с этим локально тоже хранится при клонировании :)

2022-04-26 14:21 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга. Настроены SLO по бизнес метрикам чер
Нельзя достигнуть Платины, перепрыгнув через Голд. И так далее)

2022-04-26 14:24 UTC, voborgus commented on content/ru/knowledge/devops-maturity-matrix.md
> +В этой матрице намерено отсутствует четкие инструкции. Мы не хотели ограничивать команды в выборе средств, а указали только "Контроли", которые будут проверяться (высокоуровневые). Грубо говоря если
Указать не мне, а тем, кто будет в будущем читать и использовать эту таблицу.

2022-04-26 14:24 UTC, voborgus commented on content/ru/knowledge/devops-maturity-matrix.md
> +Также с матрицей можно ознакомиться на гугл драйв. [Тут](https://docs.google.com/spreadsheets/d/1P6wYqUcQzeoGrT0Qel0Vr4D-9FAGVPATjNCUUCgR7k8/edit#gid=1710224921)
Предлагаю перенести комментарии команд в этот пулл реквест.

2022-04-27 09:23 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Осуществляется версионный контроль используется, единый формат и централизованное хранение дистрибутивов, единая сборка для всех сред. <abbr data-toggle='tooltip' title='Команда следует
Конкретная реализация централизованного хранилища — это наше требование ко всем командам. Другие реализации не поддерживаются и запрещены.

2022-04-28 13:08 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "В централизованном VCS компании, используется практика Code Review."
Code review не имеет отношения к хранению кода. Так же, как и покрытие тестами (оно ведь отдельно)

2022-04-28 13:10 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Не првоводится.",
опечатка

2022-04-28 13:14 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "В централизованном VCS компании, используется практика Code Review."
Мне кажется, можно не дублировать два раза одно и то же требование, просто пропуск сделать в platinum. Дубли отнимают время читателя на поиск отличий. А отличий нет.

2022-04-28 13:19 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Больше 80%"
по какой метрике/шкале? я-то примерно понимаю, о чём речь, но и то до конца не уверен

2022-04-28 13:22 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Осуществляется версионный контроль дистрибутивов с использованием семантического версионирования. <abbr data-toggle='tooltip' title='Через CI тул, неважно какой. Семвер орг.'><i class=
Как связан версионный контроль и хранение? Вот что нужно при хранении, так это отдельно хранить dev версии (которые должны периодически удаляться), и отдельно релизные (10 последний релизов не должны удаляться)

2022-04-28 13:28 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Сборка",
что насчёт стабильности (повторяемости) сборки? что по скорости сборки?

2022-04-28 13:32 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Написание кода",
как насчёт версионирования кода? такое же, как и для артефактов (gitflow/релизы)

2022-04-28 13:48 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Использование инструмента управления релизами и его интеграция в процесс развертывания. Автоматическая миграция БД. Автоматический откат приложений.",
Автоматический откат в каких случаях? У нас есть типа smoke-test, стандартный healthcheck. А за пределами него не понятно, надо что-то ещё проверять или нет. Если надо, то что?

2022-04-28 13:51 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
список защищённых хранилищ можно? иначе надо переформулировать

2022-04-28 13:51 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
в централизованном vault.lmru.tech

2022-04-28 14:00 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Уведомления об сбоях ведутся через единую систему управления инцидентами и коммуникациями.",
я поддерживаю Диму

2022-04-28 14:00 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Уведомления о сбоях отправляются в неструктурированые каналы коммуникации.",
не понятно, что такое неструктурированные

2022-04-28 14:12 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Релиз и Деплой",
что насчёт требования к отказоустойчивости, доступности? веб-сервер с максимум одним инстансом на проде может получить platinum в итоге?

2022-04-28 14:18 UTC, sergey-volkov-lm requested changes
Поддерживаю Диму С. в большинстве случаев, есть собственные вопросы к содержанию

2022-06-16 08:59 UTC, Joda-repo commented on content/ru/knowledge/devops-maturity-matrix.md
> +Также с матрицей можно ознакомиться на гугл драйв. [Тут](https://docs.google.com/spreadsheets/d/1P6wYqUcQzeoGrT0Qel0Vr4D-9FAGVPATjNCUUCgR7k8/edit#gid=1710224921)
Принято

2022-06-16 09:05 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Код хранится в централизованном VCS компании, используется практика Code Review.",
Принято

2022-06-16 09:08 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Код хранится в централизованном VCS компании, используется практика Code Review."
Принято

2022-06-16 09:11 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Отсутствует автоматизация сборки.",
Принято

2022-06-16 09:46 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Осуществляется версионный контроль дистрибутивов с использованием семантического версионирования. <abbr data-toggle='tooltip' title='Через CI тул, неважно какой. Семвер орг.'><i class=
Принято

2022-06-16 09:46 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Осуществляется версионный контроль используется, единый формат и централизованное хранение дистрибутивов, единая сборка для всех сред. <abbr data-toggle='tooltip' title='Команда следует
Принято

2022-06-16 10:22 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Осуществляется версионный контроль используется, единый формат и централизованное хранение дистрибутивов, единая сборка для всех сред."
Убрал.

2022-06-16 10:22 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Cases": "Хранение артефактов сборки",
Поправил.

2022-06-16 10:23 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Cases": "Обратная связь",
Поправил.

2022-06-16 10:25 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Результаты тестов влияют на сборку.",
Поправил.

2022-06-16 10:31 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сборка падает, если не проходит проверки. Проводится проверка качества и скорости процедуры сборки.<abbr data-toggle='tooltip' title='shared-pipelline / waitQualityGate ()'><i class=
Поправил.

2022-06-16 10:50 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Cases": "Статический анализ кода",
Поправил

2022-06-16 10:50 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Интеграционное тестирование не проводится.",
Поправил

2022-06-16 10:51 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Интеграционное тестирование проводится вручную.",
Поправил.

2022-06-16 14:17 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Применяется автоматизированное контрактное тестирование с ипользованием централизованной базы контрактов."
Добавил комментарий, что это не достижимо.

2022-06-16 14:18 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Тестирование производительности не проводится в рамках процедуры поставки.",
Поправил

2022-06-16 14:26 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Тестирование ИБ не проводится.",
Поправил

2022-06-16 14:26 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Тестирование ИБ не проводится.",
Поправил

2022-06-16 14:27 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Автоматический анализа зависимостей на ИБ (OSA). Автоматическое динамическое тестирование ИБ (DAST). Автоматическое интерактивное тестирование ИБ (IAST)."
Всё из этого может быть предоставлено.

2022-06-16 14:35 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Автоматический анализа зависимостей на ИБ (OSA). Автоматическое динамическое тестирование ИБ (DAST). Автоматическое интерактивное тестирование ИБ (IAST)."
Поправил формулировки, проверь пожалуйста.

2022-06-16 14:37 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Полностью ручное тестирование или тестирование не выполняется. Нет единой системы управления тестированием.",
Поправил.

2022-06-16 15:02 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Все тесты ведутся в Системе управления тестированием. Тесты вызываются вручную. <abbr data-toggle='tooltip' title='речь про тест-кейсы'><i class=\"fas fa-question-circle\"></i></abbr>"
Принято.

2022-06-16 15:26 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Используются статические среды, выделяемые по запросу. Развертывание производится в ручном режиме. ",
Поправил.

2022-06-16 15:28 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Автоматический анализа зависимостей на ИБ (OSA). <abbr data-toggle='tooltip' title='Jfrog for dev/stg/uat/prod.'><i class=\"fas fa-question-circle\"></i></abbr>",
Поправил.

2022-06-16 15:41 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Используются статические среды, выделяемые по запросу. Автоматическая установка скриптом, запускаемым вручную. Ручные smoke-тесты после развертывания. ",
Абсолютно согласен добавил новый пункт в секции тестирование как smoke тестирование.

2022-06-16 15:45 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Используются статические среды, выделяемые по запросу. Автоматическая установка с применением единообразных сценариев развертывания, включая настройки. Автоматическая проверка установки
Убрал про статистические среды. Выделил в отдельную секцию Smoke тестировение.

2022-06-16 15:47 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Используются статические среды, выделяемые по запросу. Автоматическая установка с применением единообразных сценариев развертывания, включая настройки. Автоматическая проверка устано
Кажется что там про другое в другой момент разработки.

2022-06-16 15:47 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Используются статические среды, выделяемые по запросу. Автоматическая установка с применением единообразных сценариев развертывания, включая настройки. Автоматическая проверка устано
Поправь меня если я не прав.

2022-06-16 15:47 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Cases": "Развертывание",
Кажется, что это не правильно.

2022-06-16 15:50 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Откат приложений осуществляется вручную. Использование инструмента управления релизами и его интеграция в процесс развертывания. ",
Не согласен. Я попробую согласовать с Пашей.

2022-06-16 15:51 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Использование инструмента управления релизами и его интеграция в процесс развертывания. Автоматическая миграция БД. Автоматический откат приложений. Автоматическое Canary/Blue-Green
Не согласен. Я попробую обсудить с Пашей

2022-06-16 15:55 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Автоматический запуск тестов с помощью централизованного инструмента развертывания. Автоматический запуск тестов с помощью централизованного инструмента развертывания. <abbr data-toggle=
Каждый пункт является отдельным. Мы договорились на встрече.

2022-06-16 16:12 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Секреты хранятся и используются с соблюдением требований информационной безопасности. <abbr data-toggle='tooltip' title='Можно проверить наличие секретов по репозиторию на портале тех
Убрал.

2022-06-16 16:13 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Секреты хранятся и используются с соблюдением требований информационной безопасности. <abbr data-toggle='tooltip' title='Самые часто используемые типы секретов:Privileged account crede
"Соответствует минимальным требованиям безопасности." речь же про секреты, кажется то что есть более понятно

2022-06-16 16:14 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
Секреты могут хранится в vault, Github secrets, Jenkins Credentials и.т.д.

2022-06-16 16:15 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
Закрываем коммент ?

2022-06-16 16:15 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ. Секреты для прода не используются в других окру
Ну дает примеры комент разве плохо ? Людям понятнее.

2022-06-16 16:23 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сбор и анализ логов ведется через инструмент хранения и визуализации. Логирование ведется согласно корпоративному стандарту."
@altokarev Есть такие правила ?

2022-06-16 16:28 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Bronze": "Сбор метрик ведется через корпоративный инструмент мониторинга.",
@altokarev что у нас используется?

2022-06-17 07:01 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга. Настроены SLO по бизнес метрикам чер
Добавил пункт Как работать с таблицей

2022-06-17 07:10 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Не првоводится.",
Каждый пункт является обособленым, дублирование проще воспринимается у человека который только взял таблицу чем "лесенка". Опечатку поправил.

2022-06-17 07:10 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "В централизованном VCS компании, используется практика Code Review."
Мы обсуждали это и решили оставить дублирование потому-что так выглядит проще.

2022-06-17 07:12 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Больше 80%"
Ну тут очевидно вроде, 100% Всё покрыто coverage тестами. В SonarQube есть метрика.

2022-06-17 07:12 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Больше 80%"
Согласен @sergey-volkov-lm

2022-06-17 07:19 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Больше 80%"
Не очень, я предлагаю узнать и указать название конкретного алгоритма расчёта покрытия кода. Это jacoco?

2022-06-17 07:24 UTC, sergey-volkov-lm commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
ну я бы добавил разъяснение, какие хранилища допускаются

2022-06-17 07:26 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Осуществляется версионный контроль дистрибутивов с использованием семантического версионирования. <abbr data-toggle='tooltip' title='Через CI тул, неважно какой. Семвер орг.'><i class=
@pavelchalyk  Как думаешь добавить ?

2022-06-17 07:27 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Сборка",
@pavelchalyk Как думаешь добавить ?

2022-06-17 07:32 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Откат приложений осуществляется вручную. Использование инструмента управления релизами и его интеграция в процесс развертывания. ",
Да указал

2022-06-17 07:33 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Использование инструмента управления релизами и его интеграция в процесс развертывания. Автоматическая миграция БД. Автоматический откат приложений.",
Ну когда понадобиться откат а тут решает команда когда они хотят отката. @sergey-volkov-lm

2022-06-17 07:33 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Секреты хранятся и используются с соблюдением требований информационной безопасности. Секреты хранятся в одном из защищенных хранилищ.",
Добавил.

2022-06-17 07:34 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Уведомления о сбоях отправляются в неструктурированые каналы коммуникации.",
@p-yakushin  Помоги, пожалуйста.

2022-06-17 07:40 UTC, Joda-repo commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Релиз и Деплой",
Ну голд да, платинум наверное нет "Автоматическое Canary/Blue-Green развертывание." из -за этого пункта.

2022-06-17 10:56 UTC, VladislavIvanovQA commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Не проводится.",
Я бы добавил что есть тест кейсы ручные

2022-06-22 09:00 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Написание кода",
Версионирование по семверу у нас уже где-то пососедству описано, а вот git/github flow я б в дальнейших редакциях рассмотрел, может и стоит добавить) А сейчас положить это в беклог чтоб на следующей итерации не забыть это обсудить)

2022-06-22 09:07 UTC, voborgus commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Проводится регулярный анализ инфраструктуры или контейнеров на соответствие требований ИБ.<abbr data-toggle='tooltip' title='Рекомендуемые средства: Qualys или Aqua'><i class=\"fas f
Это с вашей стороны видно, а со стороны обывателя это "Тестирование безопасности". Сейчас целый пункт только для platinum уровня создан (который сейчас во многом не достижим), поэтому для компактности предлагаю либо совсем его убрать, либо всё-таки унести в единый пункт про тестирование безопасности), хоть и возможно немного пожертвуя точностью определения.

2022-06-22 14:14 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга.<abbr data-toggle='tooltip' title='Доступ
ребята, мы специально избегали указания конкретных инструментов, потому что как только инструмент сменится - матрица потеряет актуальность. вчера был динатрейс, сегодня его уже нет

2022-06-22 14:17 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Сбор метрик ведется через корпоративный инструмент мониторинга. Настроены SLO по техническим метрикам через корпоративный инструмент мониторинга.<abbr data-toggle='tooltip' title='Доступ
> При хранении кода в гите, код одновременно с этим локально тоже хранится при клонировании :)

Дима имхо если разжевывать каждый пункт и добиваться единственно возможной трактовки каждого пункта - матрица превратится в огромную простыню на 50 экранов и читать ее никто не будет, поэтому при возникновении вопросов трактовки имхо проще обсуждать с конкретными индивидуумами

2022-06-22 14:18 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Gold": "Уведомления об сбоях ведутся через единую систему управления инцидентами и коммуникациями.",
избегаем указания конкретных инструментов. завтра опсжени возможно сменится на pagerduty или онпремисный goalert или аналог

2022-06-22 14:27 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Platinum": "Сборка падает, если не проходит проверки. Проводится проверка качества и скорости процедуры сборки.<abbr data-toggle='tooltip' title='shared-pipelline / waitQualityGate ()'><i class=
в данном случае речь про то, что команда следит за тем, что не происходит деградация сборки, сегодня билд собирается за 2 минуты и всем ок, завтра билд занимает полчаса, и команде по-прежнему ок, потому что можно подольше покурить - такой подход не может расчитывать на платинум статус.
результаты тестов могут влиять например только на сборку из мастера, но не фейлить дев сборки. в платинуме подразумевается, что невозможно собрать билд, если не проходят юнит тесты или новый код не покрыт тестами к примеру

2022-06-22 14:31 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Сборка",
тут речь про то, что код собирается единожды и далее гоняется по всем средам и тестам. большое количество команд пересобирает код под каждую среду, в результате чего тестируют одно, а на продакшен льют другое
скорость сборки упоминается в предыдущих пунктах в платинуме
deprecated функции - в целом возможно неплохо, но в один момент команда потеряет platinum статус только из-за того, что не успела отрефакторить пайплайн. deprecated функции обычно работают какое-то время и перестают работать в определенный момент, что приводит к поломке пайплайна, но обычно deprecated функции не запрещено использовать, но на свой страх и риск

2022-06-22 14:39 UTC, pavelchalyk commented on content/ru/knowledge/maturity-matrix.json
> +    "Silver": "Уведомления о сбоях отправляются в неструктурированые каналы коммуникации.",
неструктурированные - этим словом покрываются кейсы отправки алертов в личку в телегу, в общие каналы в телеге, в почту, напрямую в слак и тп

2022-06-23 14:30 UTC, nepeta-cataria commented on content/ru/knowledge/maturity-matrix.json
> +    "Area": "Сборка",
Непонятно чем **Gold** пункт 

> Используется, хранение дистрибутивов в Artifactory

 отличается  от **Platinum** 

> Используется, **единый формат** и централизованное хранение дистрибутивов в Artifactory

Что значит единый формат? Формат чего? Имени? Типа? 
Нужны примеры

2022-07-20 14:38 UTC, voborgus approved these changes

2022-07-20 14:39 UTC, merged